### ISSUE TITLE
Cinnamon: Styles not available outside of Mint

### ISSUE THREAD

**Issue by SantiBurgos1089** [linuxmint/mint21.2-beta#23]
SCENARIO:
My apologies if this issue might not be exactly something "deal breaker", I was testing Mint 21.2 and I realize that the styles section that you showed is not available outside of Linux Mint (I am testing in Arch Linux, Manjaro and other Arch derivatives), since I don't know if this issue might be with the distribution itself, the packaging or something that I have missed somehow I just wanted to check if there is something that the responsible have to do in order to "fix it"

Apologies if the screen appears in Spanish, this is the language I have setup for some particular tests

EXPECTED RESULT:
When installing a theme that includes the styles configuration it should appear in the Cinnamon section (showing Linux Mint as example)

![Info Linux Mint](https://github.com/linuxmint/mint21.2-beta/assets/137421608/5ca0c48a-3c22-47fe-bd21-5aa01f30a13e)

![Styles on Mint](https://github.com/linuxmint/mint21.2-beta/assets/137421608/59f765d4-9f71-4882-8c9d-0767f19cbdcd)

ACTUAL RESULT:

When installing a theme that includes the styles configuration, it doesn't appear in the Cinnamon themes section (showing Manjaro as example and I have installed mint-l-theme, which has its own style configuration file)

![Info Arch Manjaro](https://github.com/linuxmint/mint21.2-beta/assets/137421608/c995993b-7174-4c16-8670-650307781bd2)

![Styles on Arch](https://github.com/linuxmint/mint21.2-beta/assets/137421608/f3d74746-6205-4ee1-91ba-00616af43ef0)

**Comment by fredcw** [comment]
I copied the file `/usr/share/cinnamon/styles.d/22_mint-artwork.styles` from Mint to Manjaro and it fixes the problem. So I guess it's an Arch/Manjaro packaging issue. Maybe this file is supposed to be distro specific because another distro may not include Mint-X and Mint-Y themes by default. Not sure how this is supposed to work.

**Comment by SantiBurgos1089** [comment]
@fredcw Interesting, I did the same thing and also copied and created another 2 separate files, one for Mint-Y and another for Mint-X along with the Mint-L, it seems that only the Mint-L is having issues, because if I add the "customized versions" of Mint-Y and Mint-X along with the mint-artwork and the Mint-L, only the Mint-L doesn't show up no matter what (and the others doesn't give any conflict despite 3 files having the same content)

**Comment by fredcw** [comment]
@SantiBurgos1089 It seems you have to install the mint-l-icons for the Mint-L variations to show up.

**Comment by SantiBurgos1089** [comment]
@fredcw true, it seems that somehow if you have one item missing on the style configuration, the entire style doesn't show up no matter what.

It seems like I need to keep analyzing how styles works and what does it takes to actually show up to ease the settings to the user (I saw the announcement on March regarding it but I'm still unable to understand how it works completely, specially since I'm the one in charge of packaging mint themes and icons in Arch)

@clefebvre I will close this, and once again, I apologize in case this wasn't considered as a deal breaker

**Comment by fredcw** [comment]
It seems to me that there are two possible ways of packaging mint themes. Put the Mint-Y, Mint-X and Mint-L themes, icon themes and cursor themes into a single package with the .style files or keep things as they are with each component separate. The first option is the only way to avoid confusion when is comes to the simplified settings feature but having 3 themes, 3 icon themes and a cursor theme in one package seems a bit much. You can't for instance separate Mint-Y and Mint-L themes/icon themes because they both require the Bibata-Modern-Classic cursor theme for them to appear in simplified settings and having this cursor theme in two different packages puts the packages in conflict. You can only put all 3 themes+icon themes+cursor theme in one package. The second option, having the Mint themes/icon themes/cursor themes in separate packages and having the .style files in say the cinnamon package is going to lead to ongoing confusion for anyone using Cinnamon desktop on any distro other than Mint as they install one of the Mint themes and wonder why the theme is missing in the simplified settings.

A solution to this would seem to be that the theme color options should show up in the simplified settings even if the associated icon themes and cursor themes are not installed. A little warning message in the dialog could state either that the theme options are unavailable because the relevant icon theme or cursor theme is not installed or the color options would still be available with a message that the theme is incomplete because of missing icon themes. Or simply have no warning message and just have the color options available and ignore the missing icon themes if they're not installed.

I think this last option is most appropriate because when people choose a color variation for a theme, they probably don't want the icon and cursor theme to change as well anyway.
