### ISSUE TITLE
White Lines on Presentation Screen

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/mint21.2-beta#32]
1. Open LibreOffice -> Impress
2. Create an empty slide-show and set the background of the slide dark
3. Start presentation => some white vertical and horizontal lines are visible (screen should be completely black)

Position of the lines varies with the screen-layout of the presentation (16:3, 4:3, 16:10)

Attached an image with the 3 screenshots
![WhiteLinesOnPresentationScreen](https://github.com/linuxmint/mint21.2-beta/assets/47174957/79d05feb-40c9-4a76-8499-88e9f67d3ead)

**Comment by LinuxOnTheDesktop** [comment]
This could be an Impress bug and specifically [this one](https://bugs.documentfoundation.org/show_bug.cgi?id=136940). Did you have the problem on an earlier version of Mint?

**Comment by MenthaSuaveolens** [comment]
Yes, I have it also on Mint 21. I don't think that the bug applies to the bug you mentioned because here the white lines are along the border of the "screen", where the LO-bug is talking about white vertical lines through the image. I'll guess it's a bug in muffin.

**Comment by LinuxOnTheDesktop** [comment]
Aha. There was a similar - but not identical - bug, somewhere in Mint, a year ago, and which got fixed. See [here](https://github.com/linuxmint/cinnamon/issues/10262).

**Comment by DaveBlack** [comment]
Hi,
This bug has been fixed in a recent version of LibreOffice.

You can upgrade using the official LibreOffice PPA, or try the Flatpak version (Flatpak version seems to launch slower).
https://launchpad.net/~libreoffice/+archive/ubuntu/ppa

**How-to:**

1. Open Terminal, then copy & paste the following...
` sudo add-apt-repository ppa:libreoffice/ppa`

(In case new to PPA's, after pressing Enter you'll be asked to enter your password).

2. Launch `Update Manger` and click `Refresh`, you should then see a LibreOffice update.

**Comment by MenthaSuaveolens** [comment]
Fine, thank you. This version 7.5.4.2 also fixes the hanging of Mail Merge Wizard.
