### ISSUE TITLE
Problem with Mint theme on VirtualBox

### ISSUE THREAD

**Issue by kacperpaczos** [linuxmint/mint21.2-beta#41]
Dark theme in VB look like this.
![image](https://github.com/linuxmint/mint21.2-beta/assets/23406555/79852f5d-e749-4529-b921-7d1bb456b999)

**Comment by LinuxOnTheDesktop** [comment]
If it's relevant: on Mint 21.1, and all the previous Mint (Cinnamon) versions I've tried, the VirtualBox 'about' text only shows when I highlight it:

![image](https://github.com/linuxmint/mint21.2-beta/assets/47056543/380f39a5-89f5-4bb6-90e6-7a4b4c226050)
 
I haven't tested 21.2 Beta, though.

**Comment by anaximeno** [comment]
This seems more of a problem from the side of Virtualbox since it doesn't happen in the version 7 of Virtualbox, from what I remeber, can you confirm that @LinuxOnTheDesktop ?

**Comment by rcalixte** [comment]
@kacperpaczos Can you share details about which theme specifically you're using here and what version of VirtualBox? I can't seem to replicate this on any of my machines with Cinnamon 5.6 or 5.8 and VirtualBox 6.1 or 7.0.

@LinuxOnTheDesktop It would be helpful to know what theme you're using as well since it seems like it could be a theming issue.

**Comment by LinuxOnTheDesktop** [comment]
@anaximeno I have had the problem with invisible 'about' text persistently, including, I think on VirtualBox 6.x.

@rcalixte: my global 'application' theme is Mint-Y-Dark Teal. Yet, changing that theme makes no difference to the content of the 'about' window (but only to its titlebar). Perhaps that is because VirtualBox is a QT app.

**Comment by JosephMcc** [comment]
This has been forever a problem with VB and other Qt apps with dark themes. Some may work better than others depending on what theme engine the Gtk2 theme is using.

**Comment by rcalixte** [comment]
I've used [Kvantum](https://github.com/tsujan/Kvantum/tree/master/Kvantum) in the past and it worked fairly well. I haven't needed to make use of it much anymore but if QT themes are problematic, it might be a good option?

**Comment by LinuxOnTheDesktop** [comment]
@JosephMcc Right. That is a shame. Still: given the popularity of VirtualBox, perhaps Mint could suggest to the VirtualBox devs a theme that would work. I think that ages ago I myself filed a bug report against VirtualBox on this matter, but the report did not get anywhere.

@rcalixte Thanks. I have used Kvantum in the past. However, I did not manage to make it solve the problem with VirtualBox, though I did not go far into the labyrinth of Kvantum's settings.

**Comment by kacperpaczos** [comment]
> This has been forever a problem with VB and other Qt apps with dark themes. Some may work better than others depending on what theme engine the Gtk2 theme is using.

What can the LM team do to resolve this issue?
@JosephMcc 

> Can you share details about which theme specifically you're using here and what version of VirtualBox? I can't seem to replicate this on any of my machines with Cinnamon 5.6 or 5.8 and VirtualBox 6.1 or 7.0.

6.1, Mint-Y-Dark, Cinnamon 5.8
@rcalixte

**Comment by rcalixte** [comment]
> 6.1, Mint-Y-Dark, Cinnamon 5.8

I think the issue is with the theme. Can you try a few things?

1. Try any of the other Mint-Y-Dark-* themes and see if you can reproduce the issue.

2. Checking the environment variables with several themes, try:
```bash
$ QT_STYLE_OVERRIDE=Fusion virtualbox
$ QT_STYLE_OVERRIDE=Windows virtualbox
$ QT_STYLE_OVERRIDE= virtualbox
```

I'm able to reproduce across different themes on 6.1 with Cinnamon 5.6 and 5.8. I haven't tested 7.0 yet.

If it ends up being a theming issue on your end, hopefully one of the environment variables works well enough for now.

**Comment by kacperpaczos** [comment]
I used the QT settings tool in Linux Mint to switch from GTK2 to Cleanlook, and it looks good (readable), but it's not dark (I use Mint Y Dark).

Why does this tool only have the GTK2 option? Where is GTK3? I don't know why GTK apps don't look good on KDE, and QT apps don't look good on GNOME. Maybe we need to update something? I think this option doesn't work well after GNOME 42.
I will try to see how it looks on pure GNOME (Ubuntu/Fedora).
![image](https://github.com/linuxmint/mint21.2-beta/assets/23406555/afb4895a-7885-426a-9621-a91f79ba7c7b)

**Comment by JosephMcc** [comment]
> What can the LM team do to resolve this issue?

Nothing. In the over ten years I've been using Linux this issue has existed. Gtk2 always had some issues with full dark themes. You used to also see it a lot in other apps like browsers. Now that most everything is Gtk3 you rarely run into the problem.

> Why does this tool only have the GTK2 option?

Because that's all Qt supports. It pulls some info from your Gtk2 theme to try and theme an app built with a completely different toolkit. You found the best solution, using the Qt settings tool. Your other option is to edit your desktop file and force VB to launch with the light version of Mint-Y. Something like `GTK_THEME=Mint-Y virtualbox`

**Comment by clefebvre** [comment]
7.0 looks OK here. 
![image](https://github.com/linuxmint/mint21.2-beta/assets/1138515/3e7ef1a5-aa3f-4dca-976e-f0475c72c400)

**Comment by LinuxOnTheDesktop** [comment]
@clefebvre Thanks, but did you try with the theme that I mentioned, Viz., the Mint-Y Dark teal theme?

**Comment by clefebvre** [comment]
It looks fine here. 

![image](https://github.com/linuxmint/mint21.2-beta/assets/1138515/94a9c206-0022-48b1-9b1c-8e98df6d475a)

**Comment by LinuxOnTheDesktop** [comment]
@clefebvre Thank you - and I'm sorry to go on, but what is the default 'style' that, by (er) default - but when using dark Mint themes - should show in Mint Cinnamon when one runs the QT5 Settings app? I ask for the following reason. I find that, on my PC, the illegible text problem disappears when I set that style to 'Windows' or 'fusion' but occurs when I use the style 'kvantum' or 'kvantum-dark' or 'breeze'

**Comment by clefebvre** [comment]
It should be "gtk2" afaik.
