### ISSUE TITLE
Some texts not translated to pt-br

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/mint21.2-beta#52]
even with the language packs installed, the update manager has texts in English.
https://postimg.cc/bs63Xd9b

**Comment by rcalixte** [comment]
This is due to incomplete or outdated translations for mintupdate. The latest translations available will be pulled in before the stable release per [this discussion](https://github.com/orgs/linuxmint/discussions/40).  It looks like [this has been fixed](https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/pt_BR/+translate?direction=backwards&memo=320&start=310) and should be fixed in the stable release of Linux Mint 21.2. If you can contribute to translations, please feel free to take a look at the [Linux Mint Translation Guide](https://linuxmint-translation-guide.readthedocs.io/en/latest).
