### ISSUE TITLE
Mate icon bug - partial symbolic "support"???

### ISSUE THREAD

**Issue by billyswong** [linuxmint/mint21.2-beta#54]
![image](https://github.com/linuxmint/mint21.2-beta/assets/33863356/d152df3b-2473-45d6-b6fe-2e3d1d9ca571)
I heard Mate become ugly in 21.2 beta because it doesn't support symbolic icons. But if so, the "correct highlight" of the icon in screenshot doesn't make sense. What is happening within Mate and the updated icon set?

And what's going on with the oversized "Help" and "About Panels" there.

**Comment by Lurux** [comment]
For the record (see [related issue](https://github.com/mate-desktop/caja/issues/1723)):

- Mate is not interested in using symbolic icons, they want to maintain a traditional look
- One of the maintainers suggested using `-gtk-icon-style: symbolic` in our GTK theme, but this doesn't seem to work consistently

**Comment by billyswong** [comment]
@Lurux I read what you wrote in https://github.com/mate-desktop/caja/issues/1723#issuecomment-1612451079 and tested `* { -gtk-icon-style: symbolic }` myself. Here is Mint-Y theme with that additional line in gtk.css
![image](https://github.com/linuxmint/mint21.2-beta/assets/33863356/eaaaf50e-8ded-452e-a1c0-7fa70d6bd0b3)

And if one compare with the current Mint-Y in 21.1 (from my desktop)
![image](https://github.com/linuxmint/mint21.2-beta/assets/33863356/b173cc9a-2db5-4e72-9b7e-831231261901)

One can see that
1. MATE is capable of symbolic icons (regardless whether it is 100% coverage)
2. The new Mint-Y icon set isn't providing appropriate symbolic icons to MATE when they could and should, thus MATE is taking the symbolic icon from fallback icon set, causing the change of symbol from trash bin to stop sign, question mark to lifebelt etc.

**Comment by Lurux** [comment]
I wouldn't say that Mate is capable of symbolic icons, it's just that GTK provides a way to forcibly convert those icons to symbolic. As previously stated, this doesn't work in all apps, and doesn't work consistently in Mate apps as far as I can tell; it's not like this isn't a hacky workaround.

As far as Mint-Y not providing the appropriate icons, I don't know how the conversation is done by GTK under the hood, but it seems plausible that the legacy fullcolor icons don't use the same naming convention as the newer symbolic ones, thus causing some problems there. I also wouldn't be surprised if some of the monochrome icons were simply outdated to begin with.

With all that said, I don't think these small inconsistencies are as big of a deal as you make it out to be. Also, if you really want a modern experience, using Cinnamon or XFCE would probably be your best bet; Mate has always been pretty explicit about the fact that they aim to retain a very old-school experience...

**Comment by billyswong** [comment]
"-gtk-icon-style: symbolic" is of course a hacky workaround, but...

In my 21.1 MATE, there is a /usr/share/icons/Mint-Y/actions/16/edit.svg, with a copy of various sizes in each size folder. In 21.2 beta, that pencil icon is deleted, with NO replacement in /usr/share/icons/Mint-Y/actions/symbolic/ ! Similar for a huge bunch of icons! add.svg? Gone. delete.svg? Gone. No wonder the icon theme in 21.2 is broken!

**Comment by clefebvre** [comment]
@billyswong themes inherit other themes, you need to check Adwaita, GNOME, HiColor, all inherited.

**Comment by billyswong** [comment]
@clefebvre MATE is capable of symbolic icons, else there won't be correct highlight in my initial screenshot. It is the reckless removal of icons in Mint-Y / Mint-L without proper symbolic replacement that causes the bug. The old regular icons are .svg already and there shouldn't be any huge barrier in assigning/setting them to be symbolic.

Edit: /usr/share/icons/Mint-Y/actions/16/color-management.svg is not a monotone icon. But it got removed in 21.2 beta too.

**Comment by Lurux** [comment]
I did a quick case study on the icons you mentioned (in LM 21.1 since that's what I had at hand)

<details><summary>Show case study</summary>

- Concerning the "edit" icon, neither Adwaita, Gnome or Hicolor provide this icon, so I have no idea what would be displayed when this icon is no longer in Mint-Y; I can only assume applications don't use this icon, as they would look broken on Gnome.
- Concerning the "add" icon, only Gnome provides this icon, but only in fullcolor variant, so I assume `gtk-icon-style: symbolic` would have no effect on this specific icon.
  - Adwaita does have a "list-add" icon in both symbolic and fullcolor variants. I assume this is what the panel's context menu uses, as they look the same as the icons in your screenshot.
- Finally, none of the icon themes currently contain a "delete" icon, so I'll assume you're talking about "edit-delete" here, which is currently present in Mint-Y.
  - Adwaita does provide this icon in both fullcolor and symbolic variants, so it seems like this wouldn't be a problem. Here again, those icons look the same as in your screenshot.
</details>

My understanding is most symbolic icons currently come from Adwaita, and this isn't going to change.

It seems like with the new Mint-Y icon theme, Mate applications will now use the non-symbolic variant of those icons, or the symbolic variant when  `gtk-icon-style: symbolic` is used.

In this case, it seems like Mint-Y's old monochrome icons were actually incorrect, and the new behavior is actually the correct one, bringing legacy apps in line with the ones that use symbolic icons.

As for the fullcolor variants of the "list-add" and "edit-delete" icons, these are classified as legacy in Adwaita, which probably indicates they shouldn't be used anymore.

---

Edit for completeness sake:

The mix of symbolic and fullcolor icons in your original screenshot legitimately seems to be a bug, though. It looks like either Mate is literally mixing icon types in its menus, or something very weird is happening with the way GTK handles fallback icons...

---

Edit 2, should have looked at this immediately:

All mint applications using symbolic icons use a star icon for their "about" button and an icon featuring a life belt for their "help" button (both located in the help menu), so I'd say the new behavior is definitely correct.

**Comment by billyswong** [comment]
![image](https://github.com/linuxmint/mint21.2-beta/assets/33863356/fc54c473-f943-4320-8951-cbc4641c8e55)

Here is the result of a proof of concept test

Procedure:
1. Open 21.2 beta VM
2. In terminal
```
sudo ln -s /usr/share/icons/Adwaita/scalable/actions/edit-delete-symbolic.svg /usr/share/icons/Mint-Y/actions/symbolic/edit-delete-symbolic.svg
sudo update-icon-caches /usr/share/icons/Mint-Y
```
3. Choose Mint-Y-Dark theme
4. Relogin

Result:
The symbolic icons from Adwaita functions perfectly as an symbolic icon in Mint-Y icon theme, without gtk.css hacks. This proves Mate desktop can do symbolic icon theme. Their preference in fullcolor icon is just a preference, not a restriction.

**Comment by Lurux** [comment]
Hmmm, something weird is happening in this menu.

It looks like maybe GTK is searching for the symbolic version of an icon before falling back to the inherited icon themes ?

From [this commit](https://github.com/linuxmint/cinnamon/commit/65149edc647c0490c7de1f54bd6f68e21fee46cc), my understanding is GTK uses different rules when looking up fallback icons depending on the way they were added to the application, and my theory is the discrepancies we observed with the gtk-icon-style hack are also caused by this.

If that's the case, it looks like your trick would indeed give "symbolic icon" ability to Mate, but I'm not sure if it would work any better than the gtk-icon-style hack, due to the same reasons.

@mtwebster do you have any idea if this is correct ?

**Comment by billyswong** [comment]
@Lurux The gtk-icon-style hack polluted some categories and applications icons in mintmenu to also become symbolic. Therefore I see that as a less desirable hack.

**Comment by Lurux** [comment]
Ah, yeah - with this trick we could target only action icons, that's a fair point.

**Comment by clefebvre** [comment]
> It looks like maybe GTK is searching for the symbolic version of an icon before falling back to the inherited icon themes ?

Absolutely. It's a pity it's been designed this way, but that's what's going on alright. Application-side, mate-panel doesn't specify any type preference (between fullcolor and symbolic), so we get an inconsistent mix and match.

Michael is working on this issue. A testing tool was added to troubleshoot icon inheritance in mint-dev-tools.

**Comment by billyswong** [comment]
![image](https://github.com/linuxmint/mint21.2-beta/assets/33863356/c74661c1-f57c-450b-bb77-2ebd6c61d531)

Proof of concept 2:
1. Open **21.1** VM (not 21.2 beta)
2. In terminal
```
sudo mv /usr/share/icons/Mint-Y/actions/16/edit-delete.svg /usr/share/icons/Mint-Y/actions/16/edit-delete-symbolic.svg
sudo mv /usr/share/icons/Mint-Y/actions/22/edit-delete.svg /usr/share/icons/Mint-Y/actions/22/edit-delete-symbolic.svg
sudo update-icon-caches /usr/share/icons/Mint-Y
```
3. Choose Mint-Y-Legacy theme
4. Relogin
5. (Add "New Panel" so one can highlight the "Delete this panel" entry)

Discovery:
The help and about icons in the original Mint-Y icon theme is tricky. There is a strange mix of monotone and color icons depending on what size they are. But if we put them aside, all other monotone icons could be just a matter of bulk rename and relink and they will be merrily transformed into "symbolic" type.

Edit: An icon changing color depending on whether one is using Hi-DPI or not ... should have been considered a bug anyway. We shouldn't need to maintain the strange monotone/color mix status quo.

**Comment by billyswong** [comment]
@Lurux
> All mint applications using symbolic icons use a star icon for their "about" button and an icon featuring a life belt for their "help" button (both located in the help menu), so I'd say the new behavior is definitely correct.

The "?" and "i" characters as icons for "help" and "about" have been there since Mint-X icon theme, albeit styled a little differently.

**Comment by billyswong** [comment]
Observation: the "symbolic" folder name in Mint icon themes is misleading. In Adwaita icon theme, it is labeled more correctly, as "scalable". Throughout the experiments in this thread, it is clear whether an icon is "symbolic" depends on the file name, not folder name.

Edit: Mint-X also uses "scalable" in folder name

**Comment by billyswong** [comment]
![image](https://github.com/linuxmint/mint21.2-beta/assets/33863356/e548db8a-601f-4330-8d70-8ddb051f6eed)

Proof of concept 3
(Mint Mate 21.1 VM, use Mint-Y-Legacy-Darker theme)
```
sudo mv /usr/share/icons/Mint-Y/actions/16/view-refresh.svg /usr/share/icons/Mint-Y/actions/16/view-refresh-symbolic.svg
sudo mv /usr/share/icons/Mint-Y/actions/22/view-refresh.svg /usr/share/icons/Mint-Y/actions/22/view-refresh-symbolic.svg
sudo update-icon-caches /usr/share/icons/Mint-Y
```

So our Mint-Y / Mint-Y-Legacy / Mint-L  "Darker" theme has been bugged for many years since the beginning? And Mint Mate shove it under the rug by hiding the "main toolbar" in Caja in later Mint Mate default installation? 😱
(Only the modded reload icon functions properly for both menu bar and toolbar.)

**Comment by billyswong** [comment]
@mtwebster
Hi any news of the monotone icons preserving as symbolic? Or shall I start working on a fork for that to users who want a genuine "legacy" icon theme?

**Comment by mtwebster** [comment]
Essentially you can't provide symbolic actions without also providing their color counterparts, otherwise the theme will fall back to those symbolics  before returning the proper color icon from an inherited theme.

For example, I want the fullcolor 'window-close' icon. If I leave our own 'window-close-symbolic' icon in our theme, I get that symbolic one, only rendered as a normal icon, and depending on how I use the icon, it may not even be rendered as a symbolic (recolored based on the theme).
![image](https://github.com/linuxmint/mint21.2-beta/assets/262776/44b0e36a-8c0d-406b-852f-3e2e7e57649f)

If I remove that symbolic icon, I get a proper inheritance:
![image](https://github.com/linuxmint/mint21.2-beta/assets/262776/f224decf-e897-4857-bf54-02a4b18e5df1)

The problem with the off-sized color 'Help' and 'About panels' icons in the original post is because the 16px version of those color icons weren't in our theme, though larger ones were - scaling won't 'automagically' occur unless you specifically force the size in the code, and in this case, mate-panel doesn't do that.

Current appearance of the original menu based on current Mint-Y git after removing our symbolics:
![image](https://github.com/linuxmint/mint21.2-beta/assets/262776/de810ad3-beab-4969-8663-0693070ccb04)

-- tool created for lookup tests - https://github.com/linuxmint/mint-dev-tools/blob/master/usr/bin/mint-test-icon-lookup


edit: Just want to add, we know these color icons we're inheriting are considered 'legacy' by Gnome, and we'll probably eventually recreate our own proper action icons. but being this close to release, removing our remaining symbolics was the least impactful way of addressing this.

**Comment by billyswong** [comment]
@mtwebster 
I see. So this is an difference in expectation or difference in goal. In my worldview, the GTK icon scheme never exist a true way to specify "I want color icons only. Don't give me symbolic." The action icons in Mint-X is mostly monotone, with subtle gradient. The action icons in original Mint-Y is in a purer form of monotone, easy to reassign them to be symbolic.

Therefore, when I first heard the Mint-L/Mint-Y icon themes is going to remove monotone icons and keep symbolic icons only, I totally expected all the existing monotone icons would migrate and perform as symbolic icons. From all the rename and relink experiments throughout last week, I am seeing applications that can't handle symbolic icons (such as Transmission) fallback gracefully to legacy Adwaita icons. I am not seeing any applications in the wild that can't render symbolic icons as symbolic yet still pick the symbolic icons.

But at this point, I can rationalize that it is too late to perform thorough check for icon handling behaviour for all applications. Better be unstylish than risking dysfunctional for dark theme users. Thanks for all the efforts.
