### ISSUE TITLE
The window-close icon is missing.

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint21.2-beta#76]
The window-close-symbolic icon is missing from the Mint-Y icon theme as shown in the screenshot below:

![Captura de tela de 2023-07-07 21-11-3](https://github.com/linuxmint/mint21.2-beta/assets/59381215/c8cd2149-e206-4045-8792-7ae85e8d73e6)

![Captura de tela de 2023-07-07 21-11-39](https://github.com/linuxmint/mint21.2-beta/assets/59381215/4fc068ac-564f-4619-8f65-eee7e43a1e1e)

**Comment by claudiux** [comment]
The `window-close-symbolic` icon is well present.

![Screenshot from 2023-07-08 10-59-38](https://github.com/linuxmint/mint21.2-beta/assets/33965039/d1cfbb09-b181-4711-ba67-2127fe8ab02a)

**Comment by claudiux** [comment]
But yes, this icon and many others have been removed from this folder in https://github.com/linuxmint/mint-y-icons/commit/bb7625b91493825a7e68fb9a58bb7350398cc85e#diff-e79c0e958dec0f9180ba24ddee710cc4a1639a46e53aa0a5bf6b09f7f9086832

**Comment by claudiux** [comment]
Ping @mtwebster

**Comment by mtwebster** [comment]
It is inherited from Adwaita/gnome now.

We removed most color action icons to rely on theme inheritance instead. Unfortunately, the way icon theme look-ups work, if you want a 'window-close' icon and window-close-symbolic is in the current theme, that symbolic will be returned instead of the color icon with the *exact* name from an inherited theme.

So basically, we can't provide a symbolic icon and *not also provide matching color icons*, or else theme inheritance doesn't work properly.

ref:
https://github.com/linuxmint/mint21.2-beta/issues/8
https://github.com/linuxmint/mint21.2-beta/issues/54
